/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialog;

import java.awt.Color;
import java.awt.Dimension;

/**
 *
 * @author Leonardo
 */
public class NewPlayerDlg extends javax.swing.JDialog {

    /**
     * Creates new form NewPlayerDlg
     */
    private Dimension screensize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
    private int hoeheSchirm = (int) screensize.getHeight();
    private int breiteSchirm = (int) screensize.getWidth();
    private Color c = null;

    public NewPlayerDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setBounds(breiteSchirm * 2 / 3, hoeheSchirm / 3, breiteSchirm / 6, hoeheSchirm / 6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btFarbe = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btStarten = new javax.swing.JButton();
        btBeenden = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(4, 2));

        jLabel1.setFont(new java.awt.Font("Old English Text MT", 1, 18)); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        getContentPane().add(tfName);

        jLabel2.setFont(new java.awt.Font("Old English Text MT", 1, 18)); // NOI18N
        jLabel2.setText("Farbe");
        getContentPane().add(jLabel2);

        btFarbe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btFarbe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFarbeActionPerformed(evt);
            }
        });
        getContentPane().add(btFarbe);

        jLabel3.setFont(new java.awt.Font("Old English Text MT", 1, 18)); // NOI18N
        jLabel3.setText("Schiff");
        getContentPane().add(jLabel3);
        getContentPane().add(jLabel4);

        btStarten.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        btStarten.setText("Starten");
        btStarten.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btStarten.setContentAreaFilled(false);
        btStarten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStartenActionPerformed(evt);
            }
        });
        getContentPane().add(btStarten);

        btBeenden.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        btBeenden.setText("Beenden");
        btBeenden.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btBeenden.setContentAreaFilled(false);
        btBeenden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBeendenActionPerformed(evt);
            }
        });
        getContentPane().add(btBeenden);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFarbeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFarbeActionPerformed
        ColorChooserDlg cdlg = new ColorChooserDlg(this,true);
        cdlg.setVisible(true);
        if (cdlg.isC()) {
            Color c = cdlg.getC();
            this.btFarbe.setBackground(c);
        } else {
            System.out.println("Fehler bei der Farbübergabe!!!");
        }
    }//GEN-LAST:event_btFarbeActionPerformed

    private void btStartenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStartenActionPerformed

    }//GEN-LAST:event_btStartenActionPerformed

    private void btBeendenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBeendenActionPerformed
        dispose();
    }//GEN-LAST:event_btBeendenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewPlayerDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewPlayerDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewPlayerDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewPlayerDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewPlayerDlg dialog = new NewPlayerDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBeenden;
    private javax.swing.JButton btFarbe;
    private javax.swing.JButton btStarten;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
