/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialog;

import Beans.Option;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author michi
 */
public class OptionsDlg extends javax.swing.JDialog {

    /**
     * Creates new form OptionsDlg
     */
    
    private Dimension screensize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
    private int hoeheSchirm = (int) screensize.getHeight();
    private int breiteSchirm = (int) screensize.getWidth();
    
    private Option o = null;
    
    private boolean isok = false;
    
    public OptionsDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.setBounds(breiteSchirm / 3, hoeheSchirm / 3, breiteSchirm / 3, hoeheSchirm / 3);
        this.setResizable(false);
    }

    public Option getOptions() {
        return o;
    }

    public boolean isok() {
        return isok;
    }
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btFinished = new javax.swing.JButton();
        lbLeben = new javax.swing.JLabel();
        lbMunition = new javax.swing.JLabel();
        lbSpeed = new javax.swing.JLabel();
        lbRadius = new javax.swing.JLabel();
        tfLeben = new javax.swing.JTextField();
        tfMunition = new javax.swing.JTextField();
        tfSpeed = new javax.swing.JTextField();
        tfRadius = new javax.swing.JTextField();
        lbBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        btFinished.setFont(new java.awt.Font("Old English Text MT", 1, 36)); // NOI18N
        btFinished.setForeground(new java.awt.Color(255, 255, 255));
        btFinished.setText("Fertig");
        btFinished.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        btFinished.setContentAreaFilled(false);
        btFinished.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFinished(evt);
            }
        });
        jPanel1.add(btFinished);
        btFinished.setBounds(190, 290, 220, 45);

        lbLeben.setFont(new java.awt.Font("Old English Text MT", 1, 30)); // NOI18N
        lbLeben.setForeground(new java.awt.Color(255, 255, 255));
        lbLeben.setText("Leben:");
        jPanel1.add(lbLeben);
        lbLeben.setBounds(130, 20, 150, 60);

        lbMunition.setFont(new java.awt.Font("Old English Text MT", 1, 30)); // NOI18N
        lbMunition.setForeground(new java.awt.Color(255, 255, 255));
        lbMunition.setText("Munition:");
        jPanel1.add(lbMunition);
        lbMunition.setBounds(130, 90, 150, 50);

        lbSpeed.setFont(new java.awt.Font("Old English Text MT", 1, 30)); // NOI18N
        lbSpeed.setForeground(new java.awt.Color(255, 255, 255));
        lbSpeed.setText("Speed:");
        jPanel1.add(lbSpeed);
        lbSpeed.setBounds(130, 150, 130, 50);

        lbRadius.setFont(new java.awt.Font("Old English Text MT", 1, 30)); // NOI18N
        lbRadius.setForeground(new java.awt.Color(255, 255, 255));
        lbRadius.setText("Radius:");
        jPanel1.add(lbRadius);
        lbRadius.setBounds(130, 210, 130, 50);

        tfLeben.setFont(new java.awt.Font("Old English Text MT", 1, 30)); // NOI18N
        tfLeben.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfLeben.setText("100");
        jPanel1.add(tfLeben);
        tfLeben.setBounds(340, 20, 160, 40);

        tfMunition.setFont(new java.awt.Font("Old English Text MT", 1, 30)); // NOI18N
        tfMunition.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfMunition.setText("150");
        jPanel1.add(tfMunition);
        tfMunition.setBounds(340, 90, 160, 40);

        tfSpeed.setFont(new java.awt.Font("Old English Text MT", 1, 30)); // NOI18N
        tfSpeed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfSpeed.setText("8");
        jPanel1.add(tfSpeed);
        tfSpeed.setBounds(340, 160, 160, 40);

        tfRadius.setFont(new java.awt.Font("Old English Text MT", 1, 30)); // NOI18N
        tfRadius.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfRadius.setText("3");
        tfRadius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRadiusActionPerformed(evt);
            }
        });
        jPanel1.add(tfRadius);
        tfRadius.setBounds(340, 220, 160, 40);

        lbBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bilder/blasen.jpeg"))); // NOI18N
        lbBackground.setText("adsfa");
        jPanel1.add(lbBackground);
        lbBackground.setBounds(0, 0, 640, 430);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onFinished(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onFinished
        
        if(!(this.tfLeben.getText().isEmpty() || this.tfMunition.getText().isEmpty() || this.tfSpeed.getText().isEmpty() || this.tfRadius.getText().isEmpty()))
        {
        int leben = Integer.parseInt(this.tfLeben.getText());
        int munition = Integer.parseInt(this.tfMunition.getText());
        int speed = Integer.parseInt(this.tfSpeed.getText());
        int radius = Integer.parseInt(this.tfRadius.getText());
        
        o = new Option(leben,munition,speed,radius);
        isok = true;
        this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Bitte alle Daten angeben!");
            isok = false;
        }
        
    }//GEN-LAST:event_onFinished

    private void tfRadiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRadiusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRadiusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionsDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionsDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionsDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionsDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OptionsDlg dialog = new OptionsDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFinished;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbBackground;
    private javax.swing.JLabel lbLeben;
    private javax.swing.JLabel lbMunition;
    private javax.swing.JLabel lbRadius;
    private javax.swing.JLabel lbSpeed;
    private javax.swing.JTextField tfLeben;
    private javax.swing.JTextField tfMunition;
    private javax.swing.JTextField tfRadius;
    private javax.swing.JTextField tfSpeed;
    // End of variables declaration//GEN-END:variables
}
