/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialog;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BorderFactory;

/**
 *
 * @author Leonardo
 */
public class ShipChooserDlg extends javax.swing.JDialog {

    /**
     * Creates new form ShipChooserDlg
     */
    private Dimension screensize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
    private int hoeheSchirm = (int) screensize.getHeight();
    private int breiteSchirm = (int) screensize.getWidth();

    public ShipChooserDlg(NewPlayerDlg parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setBounds(breiteSchirm / 3, hoeheSchirm / 3, breiteSchirm / 3, hoeheSchirm / 3);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lbSchiff1 = new javax.swing.JLabel();
        lbSchiff2 = new javax.swing.JLabel();
        lbSchiff3 = new javax.swing.JLabel();
        lbSchiff4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btWaehlen = new javax.swing.JButton();
        btBeenden = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setLayout(new java.awt.GridLayout(2, 2));

        lbSchiff1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bilder/ship1.png"))); // NOI18N
        lbSchiff1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSchiff1MouseClicked(evt);
            }
        });
        jPanel3.add(lbSchiff1);

        lbSchiff2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bilder/ship2.png"))); // NOI18N
        jPanel3.add(lbSchiff2);

        lbSchiff3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bilder/ship3.png"))); // NOI18N
        jPanel3.add(lbSchiff3);

        lbSchiff4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bilder/ship4.png"))); // NOI18N
        jPanel3.add(lbSchiff4);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        btWaehlen.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        btWaehlen.setText("Wählen");
        btWaehlen.setToolTipText("");
        btWaehlen.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btWaehlen.setContentAreaFilled(false);
        jPanel4.add(btWaehlen);

        btBeenden.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        btBeenden.setText("Beenden");
        btBeenden.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btBeenden.setContentAreaFilled(false);
        btBeenden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBeendenActionPerformed(evt);
            }
        });
        jPanel4.add(btBeenden);

        getContentPane().add(jPanel4, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBeendenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBeendenActionPerformed
        this.dispose();
    }//GEN-LAST:event_btBeendenActionPerformed

    private void lbSchiff1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSchiff1MouseClicked
        this.lbSchiff1.setBorder(BorderFactory.createLineBorder(Color.black));
               
    }//GEN-LAST:event_lbSchiff1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShipChooserDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShipChooserDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShipChooserDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShipChooserDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ShipChooserDlg dialog = new ShipChooserDlg((NewPlayerDlg) new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBeenden;
    private javax.swing.JButton btWaehlen;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbSchiff1;
    private javax.swing.JLabel lbSchiff2;
    private javax.swing.JLabel lbSchiff3;
    private javax.swing.JLabel lbSchiff4;
    // End of variables declaration//GEN-END:variables
}
