/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialog;

import Dialog.*;
import Beans.Option;
import Beans.Player;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author michi
 */
public class WinnerDlg extends javax.swing.JDialog {

    /**
     * Creates new form OptionsDlg
     */
    
    private Dimension screensize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
    private int hoeheSchirm = (int) screensize.getHeight();
    private int breiteSchirm = (int) screensize.getWidth();
    
    private Player p;
            
    
    private boolean isok = false;
    
    public WinnerDlg(java.awt.Frame parent, boolean modal,String ausgang, String gewinner) {
        super(parent, modal);
        initComponents();
        
        this.setBounds(breiteSchirm / 3, hoeheSchirm / 3, breiteSchirm / 3, hoeheSchirm / 3);
        this.setResizable(false);
        
        this.p = p;
        this.jLabel1.setText(ausgang);
        this.lbWinner.setText(gewinner);
    }

    public boolean isok() {
        return isok;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbWinner = new javax.swing.JLabel();
        lbBeenden = new javax.swing.JLabel();
        btNeuStart = new javax.swing.JLabel();
        lbBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Du siegst!");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 20, 440, 120);

        lbWinner.setFont(new java.awt.Font("Harlow Solid Italic", 0, 36)); // NOI18N
        lbWinner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbWinner.setText("Example Text");
        jPanel1.add(lbWinner);
        lbWinner.setBounds(30, 150, 590, 70);

        lbBeenden.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        lbBeenden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBeenden.setText("Beenden");
        lbBeenden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onBeenden(evt);
            }
        });
        jPanel1.add(lbBeenden);
        lbBeenden.setBounds(350, 260, 200, 70);

        btNeuStart.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        btNeuStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btNeuStart.setText("Neu Start");
        btNeuStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onNeuStart(evt);
            }
        });
        jPanel1.add(btNeuStart);
        btNeuStart.setBounds(110, 260, 200, 70);

        lbBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bilder/blasen.jpeg"))); // NOI18N
        jPanel1.add(lbBackground);
        lbBackground.setBounds(0, 0, 640, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onBeenden(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onBeenden
        System.exit(0);
    }//GEN-LAST:event_onBeenden

    private void onNeuStart(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onNeuStart
        // keine Ahnung
    }//GEN-LAST:event_onNeuStart

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinnerDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinnerDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinnerDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinnerDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WinnerDlg dialog = new WinnerDlg(new javax.swing.JFrame(), true,null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btNeuStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbBackground;
    private javax.swing.JLabel lbBeenden;
    private javax.swing.JLabel lbWinner;
    // End of variables declaration//GEN-END:variables
}
