/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.MediaTracker;
import java.awt.Toolkit;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Leonardo
 */
public class SettingsGUI extends javax.swing.JFrame {

    /**
     * Creates new form SettingsGUI
     */
    Dimension screensize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
    private int hoehe = (int) (screensize.getHeight() / 2);
    private int breite = (int) (screensize.getWidth() / 2);
    private String backgroundImageFile = System.getProperty("user.dir")
            + File.separator + "src"
            + File.separator + "Bilder"
            + File.separator + "SettingsGUIBild.jpg";
    private Image backgroundImage;

    
´´
    public SettingsGUI() {

        Graphics g = getGraphics();
        this.setBounds((int) (screensize.getWidth() / 2 - breite / 2), (int) (screensize.getHeight() / 2 - hoehe / 2), breite, hoehe);

        MediaTracker mt = new MediaTracker(this);
        backgroundImage = Toolkit.getDefaultToolkit().getImage(backgroundImageFile);
        mt.addImage(backgroundImage, 0);
        try {
            mt.waitForAll();
//        paintComponent(g);
        } catch (InterruptedException ex) {
            Logger.getLogger(SettingsGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    protected void paintComponent(Graphics g) {
        g.drawImage(backgroundImage, 0, 0, this.getWidth(), this.getHeight(), this);
    }

//    class BackGroundPane extends JPanel {
//
//        Image img = null;
//
//        BackGroundPane(String imagefile) {
//            if (imagefile != null) {
//                MediaTracker mt = new MediaTracker(this);
//                img = Toolkit.getDefaultToolkit().getImage(imagefile);
//                mt.addImage(img, 0);
//                try {
//                    mt.waitForAll();
//                } catch (InterruptedException e) {
//                    e.printStackTrace();
//                }
//            }
//        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

                /**
                 * @param args the command line arguments
                 */
                public static void main(String args[]) {
                    /* Set the Nimbus look and feel */
                    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                     */
                    try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                            if ("Nimbus".equals(info.getName())) {
                                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                break;

                            }
                        }
                    } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(SettingsGUI.class
                                .getName()).log(java.util.logging.Level.SEVERE, null, ex);

                    } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(SettingsGUI.class
                                .getName()).log(java.util.logging.Level.SEVERE, null, ex);

                    } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(SettingsGUI.class
                                .getName()).log(java.util.logging.Level.SEVERE, null, ex);

                    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(SettingsGUI.class
                                .getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    }
                    //</editor-fold>

                    /* Create and display the form */
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            new SettingsGUI().setVisible(true);
                        }
                    });
                }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
